// Column layout copied from the CNX Pad Summary master (MAM17U South Pad Summary.xlsx).
// Ownership tab: header row 21, data starts row 22. Title-Curative tab: header row 1.

export interface PadColumn { col: string; header: string; width: number; fill: string; numFmt?: string; formula?: string }

export const OWNERSHIP_COLUMNS: PadColumn[] = [
  { col: 'A', header: 'Tract #', width: 26.3, fill: 'FFB4C6E7' },
  { col: 'B', header: 'TMP#', width: 74.3, fill: 'FFB4C6E7' },
  { col: 'C', header: 'QLA Title #', width: 34.3, fill: 'FFB4C6E7' },
  { col: 'D', header: 'WI Owner ', width: 26.7, fill: 'FFB4C6E7' },
  { col: 'E', header: 'Interest Status ', width: 28.7, fill: 'FFB4C6E7' },
  { col: 'F', header: 'QLS Agreement #', width: 36.1, fill: 'FFB4C6E7' },
  { col: 'G', header: 'Original Lessor/Grantor', width: 13.0, fill: 'FFB4C6E7' },
  { col: 'H', header: 'Original Lessee/Grantee', width: 35.6, fill: 'FFB4C6E7' },
  { col: 'I', header: 'Current Owner:BA Name', width: 56.6, fill: 'FFB4C6E7' },
  { col: 'J', header: 'Current Owner: Address', width: 51.1, fill: 'FFB4C6E7' },
  { col: 'K', header: 'BA #', width: 13.1, fill: 'FFB4C6E7' },
  { col: 'L', header: 'BA SUFFIX', width: 22.1, fill: 'FFB4C6E7' },
  { col: 'M', header: 'Effective Agreement Date', width: 18.6, fill: 'FFB4C6E7' },
  { col: 'N', header: 'Agreement Recording Information', width: 37.4, fill: 'FFB4C6E7' },
  { col: 'O', header: 'Lease Primary Term Expiration Date', width: 27.0, fill: 'FFB4C6E7' },
  { col: 'P', header: 'Lease Extension Exercised or Set-Up in QLS?', width: 18.7, fill: 'FFB4C6E7' },
  { col: 'Q', header: 'Extension Type  \n(Paid Up or Rental)', width: 13.0, fill: 'FFB4C6E7' },
  { col: 'R', header: 'Earliest Lease Extension Expiration Date', width: 22.1, fill: 'FFB4C6E7' },
  { col: 'S', header: 'Final Lease Extension Expiration Date', width: 18.7, fill: 'FFB4C6E7' },
  { col: 'T', header: 'Assignment Primary Term Expiration Date ', width: 21.6, fill: 'FFB4C6E7' },
  { col: 'U', header: 'Assignment Extension Exercised or Set-Up in QLS?', width: 18.7, fill: 'FFB4C6E7' },
  { col: 'V', header: 'Assignment Extension Expiration Date', width: 23.9, fill: 'FFB4C6E7' },
  { col: 'W', header: 'Formations Controlled By CNX', width: 28.7, fill: 'FFB4C6E7' },
  { col: 'X', header: 'Agreement Formations', width: 23.9, fill: 'FFB4C6E7' },
  { col: 'Y', header: 'ORRI, JOA Contracts to Relate', width: 24.1, fill: 'FFD9E1F2' },
  { col: 'Z', header: 'Lease in Other CNX Units?', width: 35.6, fill: 'FFB4C6E7' },
  { col: 'AA', header: 'Pooling Limitation', width: 20.1, fill: 'FFB4C6E7' },
  { col: 'AB', header: 'Pugh ', width: 16.3, fill: 'FFB4C6E7' },
  { col: 'AC', header: 'Cross-Unit Drilling/ Development/ Overlapping Units Prohibited?', width: 20.1, fill: 'FFB4C6E7' },
  { col: 'AD', header: 'Gross Agreement Acres ', width: 15.1, fill: 'FFB4C6E7' },
  { col: 'AE', header: 'TMP# Covered by Agreement', width: 79.4, fill: 'FFB4C6E7' },
  { col: 'AF', header: 'Gross Tract Acres', width: 13.4, fill: 'FFB4C6E7' },
  { col: 'AG', header: 'Resolved Gross Tract Acres', width: 15.1, fill: 'FFB4C6E7', numFmt: '0.000' },
  { col: 'AH', header: 'Resolved Gross Tract Acres in Unit', width: 15.6, fill: 'FFB4C6E7', numFmt: '0.000' },
  { col: 'AI', header: 'Executive Interest', width: 22.6, fill: 'FFB4C6E7', numFmt: '0.00000' },
  { col: 'AJ', header: 'Executive Interest Acres', width: 15.4, fill: 'FFB4C6E7', numFmt: '0.000', formula: '=AI{r}*AF{r}' },
  { col: 'AK', header: 'Executive Interest Acres in Unit', width: 13.4, fill: 'FFB4C6E7', numFmt: '0.000000', formula: '=AH{r}*AI{r}' },
  { col: 'AL', header: 'Royalty Interest Type', width: 10.9, fill: 'FFB4C6E7' },
  { col: 'AM', header: 'Owner Lease Royalty \n(RI or ORRI)', width: 16.3, fill: 'FFB4C6E7', numFmt: '0.0000' },
  { col: 'AN', header: 'Royalty Owner MI ', width: 15.1, fill: 'FFD9E1F2', numFmt: '0.00000000' },
  { col: 'AO', header: 'Royalty Owner Acres ', width: 15.6, fill: 'FFD9E1F2', numFmt: '0.00000000', formula: '=AF{r}*AN{r}' },
  { col: 'AP', header: 'Resolved Royalty Owner Acres', width: 18.9, fill: 'FFD9E1F2', numFmt: '0.00000000', formula: '=AG{r}*AN{r}' },
  { col: 'AQ', header: 'Resolved Royalty Owner Acres in Unit', width: 17.3, fill: 'FFD9E1F2', numFmt: '0.00000000', formula: '=AH{r}*AN{r}' },
  { col: 'AR', header: 'Royalty Owner % of Unit', width: 19.0, fill: 'FFD9E1F2', numFmt: '0.00000000', formula: '=AQ{r}/$B$4' },
  { col: 'AS', header: 'Royalty Owner NRI in Unit', width: 19.9, fill: 'FFD9E1F2', numFmt: '0.00000000', formula: '=ROUND(AM{r}*AR{r},10)' },
  { col: 'AT', header: 'CNX NRI in Tract', width: 17.4, fill: 'FFD9E1F2', numFmt: '0.00000000', formula: '=AR{r}-AS{r}' },
  { col: 'AU', header: 'Tax Exempt?\n(1=N) SHARES /(4=Y) NO SHARE', width: 13.3, fill: 'FFD9E1F2' },
  { col: 'AV', header: 'Tax Free?\n(1=N) SHARES /(4=Y) NO SHARE', width: 14.9, fill: 'FFB4C6E7' },
  { col: 'AW', header: 'MEG Group\n\nSee QDO codes in TEAMS', width: 13.1, fill: 'FFB4C6E7' },
  { col: 'AX', header: 'MEG Group Description\n\nSee QDO codes in TEAMS', width: 19.1, fill: 'FFB4C6E7' },
  { col: 'AY', header: 'Special Pricing or Deducts (SOD)', width: 19.6, fill: 'FFB4C6E7' },
  { col: 'AZ', header: 'Gross Royalty?', width: 14.3, fill: 'FFD9E1F2' },
  { col: 'BA', header: 'Deduct and Pricing Language: If Lease allows for deducts, copy and paste deduct language. Also, include any language regarding pricing, ', width: 162.4, fill: 'FFD9E1F2' },
  { col: 'BB', header: 'Market Enhancement Clause in Agreement?', width: 22.1, fill: 'FFD9E1F2' },
  { col: 'BC', header: 'Min Pay\n$0.01\n$25\n$50\n$100', width: 15.1, fill: 'FFD9E1F2' },
  { col: 'BD', header: '30-Day Pay \n\nN/A - CPA is 30 day Pay', width: 11.6, fill: 'FF757171' },
  { col: 'BE', header: 'Need to Recoup Prior Land/Lease Payment? (5k or more)', width: 28.9, fill: 'FFB4C6E7' },
  { col: 'BF', header: 'Does The Lease Allow for Reocupment?', width: 24.6, fill: 'FFD9E1F2' },
  { col: 'BG', header: 'MWM\n$25 MIN per well per month?', width: 17.0, fill: 'FFD9E1F2' },
  { col: 'BH', header: 'Pay Code\n\nSee QDO codes in TEAMS', width: 13.9, fill: 'FFB4C6E7' },
  { col: 'BI', header: 'PA: Does this Tract Need Apportioned? \n\nWV/OH: Does Lease Require Apportionment and Does Tract Need Apportionment?', width: 31.3, fill: 'FFD9E1F2' },
  { col: 'BJ', header: 'Date Ownership Verified Through', width: 13.6, fill: 'FFD9E1F2', numFmt: 'mm-dd-yy' },
  { col: 'BK', header: 'Approved to Pay by Land Ops Attorney', width: 16.9, fill: 'FFD9E1F2', numFmt: 'mm-dd-yy' },
  { col: 'BL', header: 'Initial Suspense Reason - Land Ops', width: 32.9, fill: 'FFD9E1F2' },
  { col: 'BM', header: 'Action Items Needed to Release Money from Suspene - Land Ops', width: 35.4, fill: 'FFD9E1F2' },
  { col: 'BN', header: 'Title Notes', width: 176.6, fill: 'FFB4C6E7' },
  { col: 'BO', header: 'Approved to Pay by D.O.', width: 19.1, fill: 'FFB4C6E7' },
  { col: 'BP', header: 'Pay/Susp Reason\n\nSee QDO codes in TEAMS', width: 16.4, fill: 'FFB4C6E7' },
  { col: 'BQ', header: 'Action Items Needed to Release Money from Suspene - D.O.', width: 48.3, fill: 'FFB4C6E7' },
  { col: 'BR', header: 'D.O Notes', width: 58.6, fill: 'FFB4C6E7' },
];

export const TITLE_CURATIVE_COLUMNS: (PadColumn & { key: string })[] = [
  { col: 'A', key: 'tract', header: 'Tract #', width: 26.3, fill: 'FFB4C6E7' },
  { col: 'B', key: 'tmp', header: 'TMP#', width: 54.9, fill: 'FFB4C6E7' },
  { col: 'C', key: 'qls', header: 'QLA Title #', width: 36.0, fill: 'FFB4C6E7' },
  { col: 'D', key: 'opinionDate', header: 'Title Opinion Date ', width: 30.4, fill: 'FFB4C6E7' },
  { col: 'E', key: 'certDate', header: 'Current Title Cert. Date', width: 31.1, fill: 'FFB4C6E7' },
  { col: 'F', key: 'additionalProduct', header: 'Additional Title Product Needed?', width: 36.9, fill: 'FFB4C6E7' },
  { col: 'G', key: 'additionalOrdered', header: 'Additional Title Product Ordered', width: 32.7, fill: 'FFB4C6E7' },
  { col: 'H', key: 'heirship', header: 'Heirship', width: 24.1, fill: 'FFB4C6E7' },
  { col: 'I', key: 'heirshipName', header: 'Heirship Name', width: 51.4, fill: 'FFB4C6E7' },
  { col: 'J', key: 'land', header: 'Land: Action Items', width: 196.6, fill: 'FFB4C6E7' },
  { col: 'K', key: 'thirdParty', header: 'Third Party/Transactions: Action Items', width: 100.7, fill: 'FFB4C6E7' },
  { col: 'L', key: 'mapping', header: 'Title Mapping: Action Items', width: 110.1, fill: 'FFB4C6E7' },
  { col: 'M', key: 'title', header: 'Title: Action Items', width: 145.6, fill: 'FFB4C6E7' },
  { col: 'N', key: 'analystReview', header: 'Analyst Review Date', width: 25.0, fill: 'FFB4C6E7' },
  { col: 'O', key: 'analystUpdate', header: 'Analyst Update Review Date', width: 13.0, fill: 'FFB4C6E7' },
  { col: 'P', key: 'initialReview', header: 'Initial Review Date', width: 24.9, fill: 'FFB4C6E7' },
  { col: 'Q', key: 'finalReview', header: 'Final Review Date', width: 13.0, fill: 'FFB4C6E7' },
  { col: 'R', key: 'notes', header: 'Notes', width: 115.3, fill: 'FFB4C6E7' },
];

// Unit header block (rows 1-15) on the Ownership tab
export const OWNERSHIP_TOP_LABELS: [string, string][] = [
  ['A1', 'Unit Description'],
  ['D1', 'Land Team Responsible for Unit'],
  ['A2', 'Unit Name'],
  ['D2', 'Land Ops Attorney'],
  ['A3', 'Township/County/State'],
  ['D3', 'Landman'],
  ['A4', 'Total Acres in Unit'],
  ['D4', 'D.O. Analyst '],
  ['A5', 'Exhibit Date'],
  ['A6', 'DPU Recorded Date(s)'],
  ['D6', 'DOI Set Up '],
  ['A7', 'Well API #s in Unit '],
  ['D7', 'PROPERTY #'],
  ['A8', 'Well Names in Unit'],
  ['D8', 'PRODUCTS'],
  ['AS8', 'CNX WI & NRI in Unit'],
  ['A9', 'TiL Date'],
  ['D9', 'DPU #'],
  ['AS9', 'CNX NRI%'],
  ['D10', 'PAD TM'],
  ['AS10', 'CNX WI%'],
  ['A11', 'Important Pad Dates'],
  ['AS11', 'Cotenancy %'],
  ['A12', 'Initial Lateral Cleared For Permitting (Pad Build)'],
  ['AS12', 'Cotenancy Acres'],
  ['A13', 'Shortened Lateral(s) Cleared for Permitting'],
  ['AS13', 'JOA'],
  ['A14', 'All Laterals Cleared for Permitting'],
  ['AS14', 'Non-Op WI%'],
  ['A15', 'SPUD Approval Date'],
  ['AS15', 'Non-Op NRI%'],
];
